### ISSUE TITLE
Add #[derive(Debug)] to mpv_handler structs

### ISSUE THREAD

**Issue by emmiegit** [Cobrand/mpv-rs#1]
The structs `MpvHandler`, `MpvHandlerWithGl`, `MpvHandlerBuilder` do not have `std::fmt::Debug` implemented.

**Comment by Cobrand** [comment]
PR welcome!... Athough I'm not sure why you want Debug for MpvHandlerBuilder, is there any use case I'm not thinking of?

**Comment by emmiegit** [comment]
Well for `MpvHandlerBuilder` it's not that important, but we may as well add it in case somebody needs it. Maybe for debugging?
